<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.10.1" />
    <PackageReference Include="AWSSDK.S3" Version="3.7.303" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlgoPlatform.Application\AlgoPlatform.Application.csproj" />
    <ProjectReference Include="..\AlgoPlatform.Domain\AlgoPlatform.Domain.csproj" />
    <ProjectReference Include="..\AlgoPlatform.Contracts\AlgoPlatform.Contracts.csproj" />
    <ProjectReference Include="..\AlgoTracing\AlgoTracing.csproj" />
  </ItemGroup>


</Project>
