<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
    <PackageReference Include="StackExchange.Redis" Version="2.10.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="9.0.6" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="9.0.6" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlgoPlatform.Application\AlgoPlatform.Application.csproj" />
    <ProjectReference Include="..\AlgoPlatform.Domain\AlgoPlatform.Domain.csproj" />
    <ProjectReference Include="..\AlgoPlatform.Infrastructure\AlgoPlatform.Infrastructure.csproj" />
  </ItemGroup>

</Project>
