# ===== build =====
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY . .

RUN dotnet restore ./AlgoPlatform.Compiler/AlgoPlatform.Compiler.csproj
RUN dotnet publish ./AlgoPlatform.Compiler/AlgoPlatform.Compiler.csproj -c Release -o /app /p:UseAppHost=false

# ===== runtime =====
FROM mcr.microsoft.com/dotnet/runtime:10.0
WORKDIR /app
COPY --from=build /app .

RUN apt-get update \
    && apt-get install -y --no-install-recommends docker.io \
    && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["dotnet","AlgoPlatform.Compiler.dll"]
