# ===== build =====
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY . .

RUN dotnet restore ./AlgoPlatform.Runner/AlgoPlatform.Runner.csproj
RUN dotnet publish ./AlgoPlatform.Runner/AlgoPlatform.Runner.csproj -c Release -o /app /p:UseAppHost=false

# ===== runtime =====
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /app .

RUN apt-get update \
    && apt-get install -y --no-install-recommends docker.io \
    && rm -rf /var/lib/apt/lists/*

ENV ASPNETCORE_URLS=http://0.0.0.0:5291
EXPOSE 5291

ENTRYPOINT ["dotnet","AlgoPlatform.Runner.dll"]

