// <auto-generated />
using AlgoPlatform.Infrastructure.Database.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlgoPlatform.Infrastructure.Database.PostgreSQL.Migrations
{
    [DbContext(typeof(AlgoPlatformDbContext))]
    partial class AlgoPlatformDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlgoPlatform.Domain.Models.Algorithm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("algorithms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Простой сортировочный алгоритм O(n^2).",
                            Name = "Bubble sort"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Сортировка выбором, O(n^2).",
                            Name = "Selection sort"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Сортировка вставками, O(n^2).",
                            Name = "Insertion sort"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Сортировка слиянием, O(n log n).",
                            Name = "Merge sort"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Быстрая сортировка, O(n log n) в среднем.",
                            Name = "Quick sort"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Поиск в глубину в графе.",
                            Name = "DFS"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Поиск в ширину в графе.",
                            Name = "BFS"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
