<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\AlgoPlatform.Contracts\AlgoPlatform.Contracts.csproj" />
    <ProjectReference Include="..\AlgoTracing\AlgoTracing.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RabbitMQ.Client" Version="7.2.0" />
    <PackageReference Include="AWSSDK.S3" Version="3.7.303" />
  </ItemGroup>

</Project>
